name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cancel_previous:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: styfle/cancel-workflow-action@0.9.1
      with:
        workflow_id: ${{ github.event.workflow.id }}
        
  build_and_test_ios:
    needs: cancel_previous
    runs-on: macos-13
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0.1'
    - uses: actions/checkout@v2
    - name: create-json
      id: create-json
      uses: jsdaniell/create-json@v1.2.1
      with:
        name: "secrets.json"
        json: '{ "oneTrustAPIKey": "${{ secrets.ONETRUST_APIKEY }}" }'
        dir: "Sources/SegmentConsentOneTrust-Tests/Resources"
    - run: xcodebuild clean -scheme SegmentConsentOneTrust test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO"

  build_and_test_tvos:
    needs: cancel_previous
    runs-on: macos-13
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0.1'
    - uses: actions/checkout@v2
    - name: create-json
      id: create-json
      uses: jsdaniell/create-json@v1.2.1
      with:
        name: "secrets.json"
        json: '{ "oneTrustAPIKey": "${{ secrets.ONETRUST_APIKEY }}" }'
        dir: "Sources/SegmentConsentOneTrust-Tests/Resources"
    - run: xcodebuild clean -scheme SegmentConsentOneTrust test -sdk appletvsimulator -destination 'platform=tvOS Simulator,name=Apple TV' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO"
 
      